config/routes.rb
Rails.application.routes.draw do
  
  root                 'static_pages#home'
  get    'help'     => 'static_pages#help'
  get    'contact'  => 'static_pages#contact'
  get    'signup'   => 'users#new'
  get    'edit'     => 'users#edit'
  get    'signin'   => 'sessions#new'
  post   'signin'   => 'sessions#create'
  delete 'signout'  => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/contact.html.erb
<% provide(:title, "Get in Contact") %>

<h1>Contact us</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
        <%= form_tag do %>
            <div class="form-group">
                <%= label_tag 'name', 'Name' %>
                <%= text_field_tag 'name', nil, class: 'form-control', placeholder: 'Your Name' %>
            </div>
           <div class="form-group">
               <%= label_tag 'email', 'Email' %>
               <%= email_field_tag 'email', nil, class: 'form-control', placeholder: 'Your Email Address' %>
           </div>
           <div class="form-group">
               <%= label_tag 'comments', 'Comments' %>
               <%= text_area_tag 'comments', nil, class: 'form-control', rows: 4, placeholder: 'Comments...' %>
           </div>
           <%= submit_tag nil, class: 'btn btn-custom' %>
            
       <% end %>
  </div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>


<div class = "container-fluid">
    <h1>Help</h1>
    <p>
      To see this page deployed in Heroku go to <a href= "https://tranquil-hollows-9377.herokuapp.com"><span class="myRegLink">here!</span></a><br>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/#help"><span class="myRegLink">Rails Tutorial help section</span></a>.<br>
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><span class="myRegLink">Ruby on Rails Tutorial </span></a>book.
    </p>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<div class="center jumbotron">
  <h1>Welcome to the HR App</h1>

  <h2>
    This is the home page for
    <a href="https://ie.linkedin.com/in/emerthornbury" class ="myA"> Emer's</a>
    HR application.
  </h2>
     <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-custom" %>
    
</div>


            