config/routes.rb
Rails.application.routes.draw do
  
  root                 'static_pages#home'
  get    'help'     => 'static_pages#help'
  get    'contact'  => 'static_pages#contact'
  get    'signup'   => 'users#new'
  get    'edit'     => 'users#edit'
  get    'signin'   => 'sessions#new'
  post   'signin'   => 'sessions#create'
  delete 'signout'  => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Created by <a href="https://ie.linkedin.com/in/emerthornbury" class ="myRegLink">E Thornbury.</a>
  
      <ul>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
       <li><a href="https://www.google.ie" target=_blank>Google</a></li>
      </ul>
  
  </small>
</footer>

app/views/layouts/_navmenu.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "ET HR", root_path, :class => "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse navbar-right">
        <ul class="nav navbar-nav">
          <!--<li class="active"><a href="#">Home</a></li>-->
          
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help",   help_path %></li>
          <li><%= link_to "Contact",   contact_path %></li>
          
              <% if logged_in? %>
              <li><%= link_to "Users", users_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
              <% else %>
                <li><%= link_to "Sign in", signin_path %></li>
              <% end %>
         
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/_shim.html.erb
 <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
 <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
 <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title><%= full_title(yield(:title)) %>
  </title>

  <%= render 'layouts/shim' %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
  <%= render 'layouts/navmenu' %> 
  
  <div class="container">
    <% if logged_in? %>
          <p>Welcome <%= @current_user.name %></p>
    <% else %>
        <p>Hello Guest, please sign in.</p>
    <% end %>
      
    
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
     <%= render 'layouts/footer' %>
     <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>